### ISSUE TITLE
Ubuntu 18.04 doesn't like this regex not being escaped.

### ISSUE THREAD

**Issue by SobieskiCodes** [luk3yx/miniirc_discord#2]
https://github.com/luk3yx/miniirc_discord/blob/f7184caf10037edd5da4d1867594045031f86a40/miniirc_discord.py#L56

Had to change `_escape_re = re.compile(r'([_\*\\])')`
to `_escape_re = re.compile(r'(\[_\*\\])')`
Not going to make a PR because im not sure what this effects in a full scope, it didn't whine about it on windows - and changing it on both windows/linux seems to resolve the issue - but it may break something else.

Also while I'm here, using the ID's didn't seem all that great for channel/user.
Personally I used

```
    def get_chan_obj(self, id):
        return self._client.get_channel(id)

    def get_user_obj(self, id):
        return self._client.get_user(id)
```
and stripped the chars `int(args[0][1:])`, `int(hostmask[0][3:-1])` (since ids are ints in rewrite)
the function itself should probably handle these and returning bad input, but I feel like this should be included in the lib as well. (this allows us to get the entire objects of the user/channel - name, id's, info about them etc)

**Comment by luk3yx** [comment]
Strangely, `re.compile(r'([_\*\\])')` throws no errors or warnings for me (Ubuntu MATE 18.04 with Python 3.6.8). What error/warning are you getting?
Changing it to `re.compile(r'(\[_\*\\])')` breaks the markdown escaping.

**Comment by SobieskiCodes** [comment]
Traceback; https://haste.discordbots.mundane.tk/gakivukuku.py

So whats weird here - i made a fresh env to try to reproduce, it didn't happen.
Ran again and this fired off the second run - im not sure exactly whats going on though to be completely honest - and could entirely be my fault. (mind you, none of this shows up on windows)

ubuntu 18.04
python 3.6.8
as well.
Below I'm going to just give my bot.py as well just incase its entirely me.
https://haste.discordbots.mundane.tk/eyeworojet.py

Will also provide terminal ss.
**https://i.imgur.com/JDpWNHX.png**

_________________________________________
Im fairly certain this is my environment - going to do some more testing.
_________________________________________
Going to go ahead and say this is on me - can't reproduce on first runs ever.

**Comment by luk3yx** [comment]
According to your traceback, your escaped regex is `r'([_\*\])')`, and the one in miniirc_discord is `r'([_\*\\])'`.
I think `miniirc_discord.py` somehow got modified (probably accidentally) and then Python was erroring because the closing bracket was not escaped.

*Off-topic feedback on `bot.py`:*
Keyword-only arguments (delimited by `*` in the documentation) to `IRC` and `Discord` are entirely optional, and you can create IRC objects like this:
```py
irc = miniirc.IRC('server', 6697, 'name', '#channel')
discord = miniirc_discord.Discord('discordtoken', 0, '')
```
I strongly recommend you use port `6697` with TLS/SSL (if `ssl` is `None` or unspecified it will automatically enable it), unless the IRC network you are using does not support it.
